#!/usr/bin/env bash



absolute_path() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

resolve_symlink() (
    if [[ $OSTYPE != darwin* ]]; then minusFarg="-f"; fi
    sym_resolved=$(readlink ${minusFarg} $1)

    if [[ -n $sym_resolved ]]; then
        echo $sym_resolved
    else
        echo $1
    fi
)


abs_kscript_path=$(resolve_symlink $(absolute_path $0))

## resolve application jar path from script location and convert to windows path when using cygwin
jarPath=$(dirname $abs_kscript_path)/kscript.jar

## expose the name of the script being run to the script itself
export KSCRIPT_FILE="$1"

if [[ $(uname) == CYGWIN* ]]; then
    jarPath=$(cygpath -w ${jarPath})
    [[ ! -z $KOTLIN_HOME ]] && KOTLIN_HOME=$(cygpath -w ${KOTLIN_HOME})
fi

# from 'kotlinc'

[ -n "$JAVA_OPTS" ] || JAVA_OPTS="-Xmx256M -Xms32M"

declare -a java_args
declare -a kscript_args

while [ $# -gt 0 ]; do
  case "$1" in
    -D*)
      java_args=("${java_args[@]}" "$1")
      shift
      ;;
    -J*)
      java_args=("${java_args[@]}" "${1:2}")
      shift
      ;;
    *)
      kscript_args=("${kscript_args[@]}" "$1")
      shift
      ;;
  esac
done

## run it
exec ${JAVACMD:=java} "${java_args[@]}" -jar ${jarPath} "${kscript_args[@]}"
