name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          # macos-10.15
          - windows-2022
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
#    defaults:
#      run:
#        shell: bash
#        working-directory: $GITHUB_WORKSPACE

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.6.21

      - name: Install dependencies for ${{ runner.os }}
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            choco install zip
            # Overwrite the WSL bash.exe
            cp /c/msys64/usr/bin/bash.exe /c/Windows/System32/bash.exe
          fi

      - name: Run tests
        timeout-minutes: 10
        shell: bash
        if: ${{ runner.os != 'Windows' }}
        run: |
          export KSCRIPT_HOME="$GITHUB_WORKSPACE"
          ./test/test_suite.sh
