name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2022
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.6.21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Install dependencies for ${{ runner.os }}
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            choco install zip
            # Overwrite the WSL bash.exe
            cp /c/msys64/usr/bin/bash.exe /c/Windows/System32/bash.exe
          fi

      - name: Run tests
        timeout-minutes: 10
        shell: bash
        run: |
          export OSTYPE=$OSTYPE
          if [ "$RUNNER_OS" == "Windows" ]; then
            export OSTYPE=Windows
          fi
          export PATH=./build/libs:${PATH}
          
          echo "OsType:         $OSTYPE"
          echo "kscript path:   $(which kscript)"
          
          if [[ "$OSTYPE" == "linux"* ]]; then
            echo "Linux test..."
            ./test/linux_suite.sh
            ./gradlew -Dtest.single=LinuxSuite integration
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            echo "MacOs test..."
            ./gradlew clean build
            ./gradlew -Dtest.single=MacSuite integration
          elif [[ "$OSTYPE" == "cygwin" ]]; then
            echo "Cygwin test..."
            echo "kscript path:   $(which kscript)"
            ./gradlew clean build
            ./gradlew -Dtest.single=CygwinSuite integration                  
          elif [[ "$OSTYPE" == "msys" ]]; then
            echo "MSys test..."
            ./gradlew clean build
            ./gradlew -Dtest.single=MsysSuite integration                  
          elif [[ "$OSTYPE" == "win32" ]]; then
            echo "Windows test..."
            ./gradlew clean build
            ./gradlew -Dtest.single=WindowsSuite integration                  
          elif [[ "$OSTYPE" == "freebsd"* ]]; then
            echo "FreeBsd test..."
            ./gradlew clean build
            ./gradlew -Dtest.single=OtherPosixSuite integration      
          else
            echo "Unknown OS"
            exit 1
          fi
