name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2022
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.6.21

      - name: Install dependencies for ${{ runner.os }}
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            choco install zip
            # Overwrite the WSL bash.exe
            cp /c/msys64/usr/bin/bash.exe /c/Windows/System32/bash.exe
          fi

      - name: Run tests
        timeout-minutes: 10
        shell: bash
        run: |
          echo "OsType:         $OSTYPE"
          export PATH=./build/libs:${PATH}
          
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            echo "Linux test..."
            ./test/test_suite.sh
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            echo "MacOs test..."
            ./gradlew clean build
            echo "kscript path:   $(which kscript)"
            kscript --help
            kscript -d "println(1+1)"
          elif [[ "$OSTYPE" == "cygwin" ]]; then
            echo "Cygwin test..."
            ./gradlew clean build
            echo "kscript path:   $(which kscript)"
            kscript --help
            kscript -d "println(1+1)"                  
          elif [[ "$OSTYPE" == "msys" ]]; then
            echo "MSys test..."
            ./gradlew clean build
            echo "kscript path:   $(which kscript)"
            kscript --help
            kscript -d "println(1+1)"                  
          elif [[ "$OSTYPE" == "win32" ]]; then
            echo "Windows test..."
            ./gradlew clean build
            echo "kscript path:   $(which kscript)"
            kscript --help
            kscript -d "println(1+1)"                  
          elif [[ "$OSTYPE" == "freebsd"* ]]; then
            echo "FreeBsd test..."
            ./gradlew clean build
            echo "kscript path:   $(which kscript)"
            kscript --help
            kscript -d "println(1+1)"
          else
            echo "Unknown OS"
            exit 1
          fi
