name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-2022
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.6.21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Install dependencies for ${{ runner.os }}
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            choco install zip
            # Overwrite the WSL bash.exe
            # cp /c/msys64/usr/bin/bash.exe /c/Windows/System32/bash.exe
            mv /c/Windows/System32/bash.exe /c/Windows/System32/wsl-bash.exe
          fi

      - name: Run tests for Posix (and MSYS on Windows)
        shell: bash
        run: |
          # For Windows this action is running MSYS Os type
          
          echo "OsType:         $OSTYPE"
          
          gradle clean assemble test || { echo 'Compilation or Unit tests failed' ; exit 1; }
          
          if [[ "$OSTYPE" == "linux"* ]]; then
            echo "Linux test..."
            ./test/linux_suite.sh
            gradle -Dos.type=$OSTYPE -DincludeTags='posix | linux' integration
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            echo "MacOs test..."
            gradle -Dos.type=$OSTYPE -DincludeTags='posix | macos' integration
          elif [[ "$OSTYPE" == "cygwin" ]]; then
            echo "Cygwin test..."
            gradle -Dos.type=$OSTYPE -DincludeTags='posix | cygwin' integration
          elif [[ "$OSTYPE" == "msys" ]]; then
            echo "MSys test..."
            gradle -Dos.type=$OSTYPE -DincludeTags='posix | msys' integration
          elif [[ "$OSTYPE" == "freebsd"* ]]; then
            echo "FreeBsd test..."
            gradle -Dos.type=$OSTYPE -DincludeTags='posix' integration      
          else
            echo "Unknown OS"
            exit 1
          fi

      - name: Run tests specific for Windows (cmd shell)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "Windows test..."
          gradle -Dos.type=$OSTYPE -DincludeTags='windows' integration 

      - name: Run tests specific for Windows (cygwin shell)
        if: runner.os == 'Windows'
        uses: cygwin/cygwin-install-action@master
        shell: bash
        run: |
          echo "Cygwin test..."
          gradle clean assemble test || { echo 'Compilation or Unit tests failed' ; exit 1; }
          gradle -Dos.type=$OSTYPE -DincludeTags='posix | cygwin' integration
