name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2022
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.6.21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Install dependencies for ${{ runner.os }}
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            choco install zip
            choco install cygwin
            # Overwrite the WSL bash.exe
            # cp /c/msys64/usr/bin/bash.exe /c/Windows/System32/bash.exe
            mv /c/Windows/System32/bash.exe /c/Windows/System32/wsl-bash.exe
          fi

      - name: Run tests specific for Windows (cmd shell)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "Windows test..."
          ./gradlew clean build
          ./gradlew -Dtest.single=WindowsSuite -Dos.type=windows integration 

      - name: Run tests specific for Windows (cygwin shell)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "Cygwin test..."
          rem ./gradlew clean build
          rem ./gradlew -Dtest.single=CygwinSuite -Dos.type=windows integration

      - name: Run tests for Posix (and MSYS on Windows)
        timeout-minutes: 10
        shell: bash
        run: |
          # For Windows this action is running MSYS Os type
          
          export PATH=./build/libs:${PATH}
          
          echo "OsType:         $OSTYPE"
          echo "kscript path:   $(which kscript)"
          
          if [[ "$OSTYPE" == "linux"* ]]; then
            echo "Linux test..."
            ./test/linux_suite.sh
            ./gradlew -Dtest.single=LinuxSuite -Dos.type=$OSTYPE integration
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            echo "MacOs test..."
            ./gradlew clean build
            ./gradlew -Dtest.single=MacSuite -Dos.type=$OSTYPE integration
          elif [[ "$OSTYPE" == "cygwin" ]]; then
            echo "Cygwin test..."
            echo "kscript path:   $(which kscript)"
            ./gradlew clean build
            ./gradlew -Dtest.single=CygwinSuite -Dos.type=$OSTYPE integration
          elif [[ "$OSTYPE" == "msys" ]]; then
            echo "MSys test..."
            ./gradlew clean build
            ./gradlew -Dtest.single=MsysSuite -Dos.type=$OSTYPE integration
          elif [[ "$OSTYPE" == "freebsd"* ]]; then
            echo "FreeBsd test..."
            ./gradlew clean build
            ./gradlew -Dtest.single=OtherPosixSuite -Dos.type=$OSTYPE integration      
          else
            echo "Unknown OS"
            exit 1
          fi
