name: installer

on:
  workflow_dispatch:
    inputs:
      kscript_version:
        description: 'KScript version to test'
        required: true
        default: '4.0.2'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2022
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.6.21

      - name: "Set KScript version"
        env:
          KSCRIPT_VERSION: ${{ github.event.inputs.kscript_version }}

      - name: Prerequisites for ${{ runner.os }}
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            choco install zip
            # Overwrite the WSL bash.exe
            cp /c/msys64/usr/bin/bash.exe /c/Windows/System32/bash.exe
          fi

      - name: Install sdkman
        shell: bash
        run: |
          bash -c "curl -s "https://get.sdkman.io" | bash"
          source "$HOME/.sdkman/bin/sdkman-init.sh"

      - name: Test installers for ${{ runner.os }}
        shell: bash
        run: |
          # sdkman
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install kscript "$KSCRIPT_VERSION"
          kscript --help
          kscript -d "println(1+1)"
          sdk uninstall kscript "$KSCRIPT_VERSION"
          
          if [ "$RUNNER_OS" == "Windows" ]; then
            true  
          elif [ "$RUNNER_OS" == "Linux" ]; then
            true
          elif [ "$RUNNER_OS" == "macOS" ]; then
            # brew
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            brew install holgerbrandl/tap/kscript
            kscript --help
            kscript -d "println(1+1)"
            brew uninstall holgerbrandl/tap/kscript
          else
            echo "Unknown OS"
            exit 1
          fi
